name: Deploy to QA

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_qa:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      MPKIT_URL: https://docskit-sandbox.staging.oregon.platform-os.com/
      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
          submodules: true

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install Dependencies
        run: |
          cd src
          npm install --legacy-peer-deps

      - name: Build
        run: |
          cd src
          npm run build

      - name: Deploy
        shell: sh
        run: |
          set -e
          npm -g install @platformos/pos-cli
          pos-cli deploy
